name: iOS workflow

on:
  push:
    branches:  
    - '*'
  pull_request:
    branches:  
    - '*'

jobs:
  build-and-test:
    runs-on: macos-13
    steps:
      - name: Check out code
        uses: actions/checkout@v3

        
      - name: Get List of Applications
        run: ls /Applications/
        
      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.0.app/Contents/Developer

      - name: Build
        run: xcodebuild build -project "Bhagavad Gita.xcodeproj" -scheme "Bhagavad Gita" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: Test
        run: xcodebuild test -project "Bhagavad Gita.xcodeproj" -scheme "Bhagavad Gita" -destination "platform=iOS Simulator,name=iPhone 14 Pro" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
